# Generated by Django 2.2.3 on 2019-07-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_prods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prods',
        ),
    ]
