# Generated by Django 2.2.3 on 2019-07-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_prods'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='employee',
        ),
    ]
