# Generated by Django 2.2.3 on 2019-07-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190710_2221'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='employee',
        ),
    ]
